openapi: 3.0.0
info:
  title: node-backend-template
  version: 0.0.1
paths:
  /v1/login:
    post:
      operationId: PostV1Login
      responses:
        "200":
          description: POST /v1/login Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      roles:
                        type: array
                        items:
                          type: string
                      accessToken:
                        type: string
                    required:
                      - id
                      - username
                      - email
                      - roles
                      - accessToken
                    example:
                      id: 60a0d0f9e0d6a53d3c9d6a2c
                      username: username
                      email: example@gmail.com
                      roles:
                        - user
                      accessToken: jwt-token-example
                required:
                  - status
                  - data
              examples:
                example1:
                  value:
                    status: success
                    data:
                      id: 60a0d0f9e0d6a53d3c9d6a2c
                      username: username
                      email: example@gmail.com
                      roles:
                        - user
                      accessToken: jwt-token-example
        "400":
          description: POST /v1/login Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
      tags:
        - auth
      requestBody:
        description: POST /v1/login request body
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
            examples:
              example1:
                value:
                  username: username
                  password: password
  /v1/register:
    post:
      operationId: PostV1Register
      responses:
        "200":
          description: POST /v1/register Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                    example:
                      message: User was registered successfully!
                required:
                  - status
                  - data
              examples:
                example1:
                  value:
                    status: success
                    data:
                      message: User was registered successfully!
        "400":
          description: POST /v1/register Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
      tags:
        - auth
      requestBody:
        description: POST /v1/register request body
        content:
          application/json:
            schema:
              allOf:
                - allOf:
                    - type: object
                      properties:
                        username:
                          type: string
                          minLength: 1
                        email:
                          type: string
                          format: email
                      required:
                        - username
                        - email
                      example:
                        username: username
                        email: example@gmail.com
                    - type: object
                      properties:
                        roles:
                          type: array
                          items:
                            type: string
                      required:
                        - roles
                      example:
                        roles:
                          - user
                          - moderator
                          - admin
                - type: object
                  properties:
                    username:
                      type: string
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                    roles:
                      type: array
                      items:
                        type: string
                  required:
                    - username
                    - email
                    - password
                  example:
                    username: username
                    email: example@gmail.com
                    password: password
                    roles:
                      - user
            examples:
              example1:
                value:
                  username: username
                  email: example@gmail.com
                  roles:
                    - user
                  password: password
  /v1/users:
    get:
      operationId: GetV1Users
      responses:
        "200":
          description: GET /v1/users Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                  data:
                    type: object
                    properties:
                      demoData:
                        type: string
                    required:
                      - demoData
                    example:
                      demoData: Querying all users succeed!
                required:
                  - status
                  - data
              examples:
                example1:
                  value:
                    status: success
                    data:
                      demoData: Querying all users succeed!
        "400":
          description: GET /v1/users Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
      tags:
        - users
      security:
        - APIKEY_1: []
  /v1/users/mod:
    get:
      operationId: GetV1UsersMod
      responses:
        "200":
          description: GET /v1/users/mod Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                  data:
                    type: object
                    properties:
                      demoData:
                        type: string
                    required:
                      - demoData
                    example:
                      demoData: Querying all users succeed!
                required:
                  - status
                  - data
              examples:
                example1:
                  value:
                    status: success
                    data:
                      demoData: Querying all users succeed!
        "400":
          description: GET /v1/users/mod Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
      tags:
        - users
      security:
        - APIKEY_1: []
  /v1/users/admin:
    get:
      operationId: GetV1UsersAdmin
      responses:
        "200":
          description: GET /v1/users/admin Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                  data:
                    type: object
                    properties:
                      demoData:
                        type: string
                    required:
                      - demoData
                    example:
                      demoData: Querying all users succeed!
                required:
                  - status
                  - data
              examples:
                example1:
                  value:
                    status: success
                    data:
                      demoData: Querying all users succeed!
        "400":
          description: GET /v1/users/admin Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
      tags:
        - users
      security:
        - APIKEY_1: []
  "/v1/users/{id}":
    get:
      operationId: GetV1UsersId
      responses:
        "200":
          description: GET /v1/users/:id Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                  data:
                    type: object
                    properties:
                      demoData:
                        type: string
                    required:
                      - demoData
                    example:
                      demoData: Querying User 12 succeed!
                required:
                  - status
                  - data
              examples:
                example1:
                  value:
                    status: success
                    data:
                      demoData: Querying User 12 succeed!
        "400":
          description: GET /v1/users/:id Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
      description: Example user retrieval endpoint.
      summary: Retrieves an user by its ID.
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          description: GET /v1/users/:id parameter
          schema:
            type: string
            pattern: /\d+/
            description: a numeric string containing the id of the user
          examples:
            example1:
              value: "12"
    post:
      operationId: PostV1UsersId
      responses:
        "200":
          description: POST /v1/users/:id Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      createdAt:
                        description: YYYY-MM-DDTHH:mm:ss.sssZ
                        type: string
                        format: date-time
                        externalDocs:
                          url: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
                    required:
                      - name
                      - createdAt
                    example:
                      name: John Doe
                      createdAt: 2021-12-31T00:00:00.000Z
                required:
                  - status
                  - data
              examples:
                example1:
                  value:
                    status: success
                    data:
                      name: John Doe
                      createdAt: 2021-12-31T00:00:00.000Z
        "400":
          description: POST /v1/users/:id Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
      description: Example user retrieval endpoint.
      summary: Updates an user by its ID.
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          description: POST /v1/users/:id parameter
          schema:
            type: string
            pattern: /\d+/
            description: a numeric string containing the id of the user
          examples:
            example1:
              value: "12"
      requestBody:
        description: POST /v1/users/:id request body
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties: {}
                - type: object
                  properties:
                    name:
                      type: string
                      minLength: 1
                  required:
                    - name
                  example:
                    name: John Doe
            examples:
              example1:
                value:
                  name: John Doe
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    APIKEY_1:
      type: apiKey
      in: header
      name: Authorization
  links: {}
  callbacks: {}
tags:
  - name: users
    description: Everything about the users
  - name: auth
    description: Everything about authentication
servers:
  - url: http://api.example.com/v1
